name: workflow1

on: 
  push:
    branches:
    - main
    - dev
  workflow_dispatch:      # enable button to manually run the workflow
  
jobs:
  job1-buildjob:
    runs-on: ubuntu-latest
    steps:  # 2 tasks or 2 steps in this workflow
      - name: task1 for printing OS Details
        run: uname -a
      - name: task2 to print hostname
        run: hostname
      - name: task3
        run: sleep 30 # do nothing for 30 seconds
      - name: task4
        run: echo "step4  and job1-buildjob completed"
  job2-testjob:
    runs-on: ubuntu-latest
    steps:  # 2 tasks or 2 steps in this workflow
      - name: task1 for printing OS Details
        run: uname -a
      - name: task2 to print hostname
        run: hostname
      - name: task3
        run: sleep 30 # do nothing for 30 seconds
      - name: task4
        run: echo "step4  and job1-testjob completed"
