name: workflow1

on: 
  push:
    branches:
    - main
    - dev
  workflow_dispatch:      # enable button to manually run the workflow
  schedule:               # schedule job to run
    - cron: "40 * * * *"  # will run workflow every hour past 40 mins

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: task1 for printing OS Details
        run: uname -a
      - name: task2 to print hostname
        run: hostname
        
