name: workflow2
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

env: 
  USER1: Jesus
jobs:
  build:
    env:
      USER2: Hurtado
      USER1: Jesus_joblevel
    runs-on: jchurtado-devops   ##this is my repo hosted in AWS runner
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: step2
        env:
          USER3: JCHURTADO
          USER1: Jesus_steplevel
        run: |  # # git clone https://github.com/admingagan/Maven-Project.git #cd Maven-Project
          ls -l
          echo "gtihub repo URL is ${{ GITHUB.REPOSITORY }} anc branch name is ${{ GITHUB.REF_NAME }} "
          echo "value for variable user1: $USER1"
          echo "This is user1: $USER1, this is user2: $USER2, and this is user3: $USER3"
          echo " value for user1 at repo level: ${{ vars.USER1 }} and server name: ${{ vars.SERVER_NAME }}  "
          echo "printing first the prod env secret variable: ${{ secrets.TOKEN1 }} "
          echo "Sending this prod env secret to new file: ${{ secrets.TOKEN1 }} " >> /tmp/jchurtado-pass
          pwd
          if: github.event_name == 'pull_request'
          run: "Print the value of user3: $USER3 "
  test:
    runs-on: jchurtado-devops
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: step3
        run: |  # # git clone https://github.com/admingagan/Maven-Project.git #cd Maven-Project
          ls -l
          echo "gtihub repo URL is ${{ GITHUB.REPOSITORY }} anc branch name is ${{ GITHUB.REF_NAME }} "
          echo "value for variable user1: $USER1"
          echo "This is user1: $USER1, this is user2: $USER2, and this is user3: $USER3"
          echo "Printing the user1 variable from DE environment: ${{ vars.USER1 }} "
          echo "Printing the secret dev env: ${{ secrets.TOKEN1 }} "
          echo "Sending the secret dev env to this file: ${{ secrets.TOKEN1 }} " >> /tmp/jchurtado-pass 
          pwd
  deploy:
    runs-on: jchurtado-devops
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: step3
        run: |  # # git clone https://github.com/admingagan/Maven-Project.git #cd Maven-Project
          ls -l
          echo "gtihub repo URL is ${{ GITHUB.REPOSITORY }} anc branch name is ${{ GITHUB.REF_NAME }} "
          echo "value for variable user1: $USER1"
          echo "This is user1: $USER1, this is user2: $USER2, and this is user3: $USER3"
          echo "printing the USER1 from PRDO environement: ${{ vars.USER1 }}"
          echo "Printing the repo level secret env: ${{ secrets.TOKEN1 }} "
          echo "Sending this repo secret level env to this file: ${{ secrets.TOKEN1 }} " >> /tmp/jchurtado-pass
          pwd
