name: workflow2
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: step2
        run: |  # # git clone https://github.com/admingagan/Maven-Project.git #cd Maven-Project
          ls -l
          echo "gtihub repo URL is ${{ GITHUB.REPOSITORY }} anc branch name is ${{ GITHUB.REF_NAME }}
          java -version
          pwd
          
