name: workflow3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        continue-on-error: true
        run: |
          eo "test step 1"
          sleep 10
      - name: step2
        run: echo "step2 run"
      - name: step3
        run: echo "step3 run"
  test1: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step 1
        run: |
          echo "test step1 "
          sleep 10
  test2: 
    runs-on: ubuntu-latest
    needs: 
      - build
      - build2
    steps:
      - name: step 1
        run: |
          echo "test step1 "
          sleep 10

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "test step 1"
          sleep 10
          
  deploy:
    runs-on: ubuntu-latest
    needs: test1
    if: ${{ always() }}
    steps:
      - name: step 1 
        run: |
          echo "test step 1"
            sleep 10
