name: workflow2
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -l
          pwd
          
